name: moneybuddy
description: "AI-powered personal finance app with intelligent transaction tracking and insights."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^16.2.1
  
  # Networking & HTTP
  dio: ^5.9.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Caching
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Media & Permissions
  camera: ^0.11.2
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1
  
  # UI & UX
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  # Assets for MoneyCA and app branding
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/animations/
  
  # TODO: Add Inter fonts when available
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
